//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioTres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejemplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejemplar()
        {
            this.PrestamoEjemplar = new HashSet<PrestamoEjemplar>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdLibro { get; set; }
        public Nullable<System.DateTime> FechaDonacion { get; set; }
        public string Prestamo { get; set; }
        public string Idioma { get; set; }
    
        public virtual Libro Libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestamoEjemplar> PrestamoEjemplar { get; set; }
    }
}
