//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioTres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamoEjemplar
    {
        public int IdEjemplar { get; set; }
        public int IdCliente { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<System.DateTime> FechaDevuelto { get; set; }
        public string EjemplarPerdido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Ejemplar Ejemplar { get; set; }
    }
}
