INSERT INTO Cliente (Nombre,FechaNacimiento,Sexo) VALUES ('Daniel Lepiz', DATEFROMPARTS(2000,1,21),'M')
INSERT INTO Cliente (Nombre,FechaNacimiento,Sexo) VALUES ('Kevin Mora', DATEFROMPARTS(1995,2,22),'M')
INSERT INTO Cliente (Nombre,FechaNacimiento,Sexo) VALUES ('Jorge Garro', DATEFROMPARTS(1999,3,23),'M')
INSERT INTO Cliente (Nombre,FechaNacimiento,Sexo) VALUES ('Jose Fallas', DATEFROMPARTS(1994,4,24),'M')
INSERT INTO Cliente (Nombre,FechaNacimiento,Sexo) VALUES ('Ricardo Gamboa', DATEFROMPARTS(1998,5,25),'M')
INSERT INTO Cliente (Nombre,FechaNacimiento,Sexo) VALUES ('Esmeralda Ramírez', DATEFROMPARTS(1993,6,26),'F')