INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Fellowship of the Ring','La comunidad del anillo',1954,1)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Two Towers','Las dos torres',1954,1)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Return of the King','El retorno del rey',1955,1)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Philosopher''s Stone','La piedra filosofal',1997,2)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Secret Chamber','La camara secreta',1998,2)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Prisoner of Azkaban','El prisionero de Azkaban',1999,2) 
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Goblet of Fire','El caliz de fuego',2000,2)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Order of the Phoenix','La orden del fenix',2003,2)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Half-Blood Prince','El principe mestizo',2005,2)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('The Deathly Hallows','Las Reliquias de la Muerte',2007,2)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('A Game of Thrones','Juego de tronos',1996,3)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('A Clash of Kings','Choque de reyes',1998,3)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('A Storm of Swords','Tormenta de espadas',2000,3)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('A Feast for Crows','Festin de cuervos',2005,3)
INSERT INTO Libro (NombreOriginal, NombreTraducido, AnioEdicion, NumeroEdicion) VALUES ('A Dance with Dragons','Danza de dragones',2011,3)